%% Search for a specified operating point for the model - findop_model.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.5 and Simulink Control Design (TM) 5.2.
%
% Generated on: 28-Apr-2019 10:56:06

%% Specify the model name
model = 'findop_model';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - findop_model/planar_vehicle/Integrator x; y; xDot; yDot; theta; thetaDot
opspec.States(1).x = [0;0;0;15;1.5708;0];
opspec.States(1).Known = [false;false;false;true;true;true];
opspec.States(1).SteadyState = [false;false;true;true;true;true];

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - findop_model/thrust fraction
opspec.Inputs(1).u = 0;

% Input (2) - findop_model/torque fraction
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(2).Known = true;

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - findop_model/V
% - Default model initial conditions are used to initialize optimization.

% Output (2) - findop_model/thetaDot
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
